name: Build & Deploy Lambda Container

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set environment variables
        run: |
          echo "ECR_URI=867725336535.dkr.ecr.eu-north-1.amazonaws.com" >> $GITHUB_ENV
          echo "IMAGE_URI=867725336535.dkr.ecr.eu-north-1.amazonaws.com/mlops-lambda:latest" >> $GITHUB_ENV

      - name: Login to ECR
        run: |
          PASSWORD=$(aws ecr get-login-password --region ${{ secrets.AWS_REGION }})
          echo $PASSWORD | docker login --username AWS --password-stdin $ECR_URI

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_URI .

      - name: Push image to ECR
        run: |
          docker push $IMAGE_URI

      - name: Update Lambda to new zip
        run: |
          zip -r function.zip .
          aws lambda update-function-code \
            --function-name "${{ secrets.LAMBDA_FUNCTION_NAME }}" \
            --zip-file fileb://function.zip
 
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/share/boost

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu     

      - name: Run training
        run: |
          python train.py \
            --epochs 2 \
            --train_samples full \
            --eval_samples 1000 \
            --precision fp16 \
            --optimizer adamw
