      - name: List repo files
        run: ls -R

      - name: Run training
        run: |
          python train.py \
            --epochs 2 \
            --train_samples full \
            --eval_samples 1000 \
            --precision fp16 \
            --optimizer adamw
